project:
  type: book
  output-dir: docs
  preview:
    port: 4400

book:
  title: "Something Understood"
  subtitle: Information about the BBC Radio 4 programme
  author: "Nick Hood"
  date: today
  date-format: "Do MMM YYYY"
  chapters:
    - index.qmd
    - su-1-episodes.qmd
    - su-2-production.qmd
    - su-3-presenters.qmd
    - su-7-episodes.qmd
    - su-8-themes.qmd
    - references.qmd
  # appendices: 
  cover-image: p0c4lm59.jpg
  favicon: favicon.ico
  downloads: [pdf]
  site-url: https://niximagery.github.io/Something-Understood
  navbar: 
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/NixImagery
      - icon: linkedin
        href: https://www.linkedin.com/in/niximagery/
  page-footer: 
    left: "Copyright Nick Hood, all rights reserved" 
    background: light
    right: 
      - icon: github
        href: https://github.com/NixImagery
      - icon: linkedin
        href: https://www.linkedin.com/in/niximagery/
  page-navigation: true
  sidebar:
    contents: auto

website:
  announcement: 
    icon: info-circle
    dismissable: true
    type: danger
    position: below-navbar
    content: "**Mark Tully 24th October 1935 -- 25th January 2026**<br>It is with great sadness that we learn of the passing Sir Mark Tully, who presented many of the episodes of Something Understood since it became a weekly broadcast in 1995. His vision of probing questions at the heart of our humanity through music, verse, prose and conversation, has brought much comfort and inspiration to so many of us. We grieve the loss of a man of great principle. Rest in peace, sir."

bibliography: ../Thesis/thesis.bib
csl: ../Thesis/chicago-author-date-no-em-dash.csl

format:
  html:
    include-in-header: 
      text: |
        <!-- Privacy-friendly analytics by Plausible -->
        <script async src="https://stats.sptr.net/js/pa-Ysqpinv0Bh8jFdBY-o2OF.js"></script>
        <script>
          window.plausible=window.plausible||function(){(plausible.q=plausible.q||[]).push(arguments)},plausible.init=plausible.init||function(i){plausible.o=i||{}};
          plausible.init()
        </script>
    theme: yeti
    page-layout: full
    toc: false
    number-depth: 0
  pdf: 
    documentclass: scrbook
    geometry: margin=2cm, bindingoffset=0.5cm
    pagestyle: headings
    papersize: a4
    fontfamily: roboto
    fontfamilyoptions: sfdefault, light
