project:
  type: book
  output-dir: docs
  preview:
    port: 4400

book:
  title: "Something Understood"
  subtitle: Information about the BBC Radio 4 programme
  author: "Nick Hood"
  date: today
  date-format: "Do MMM YYYY"
  chapters:
    - index.qmd
    - su-1-episodes.qmd
    - su-2-production.qmd
    - su-3-presenters.qmd
    - su-7-episodes.qmd
    - su-8-themes.qmd
    - references.qmd
  # appendices: 
  cover-image: p0c4lm59.jpg
  favicon: favicon.ico
  # repo-url: https://github.com/NixImagery/Something-Understood
  downloads: [pdf]
  site-url: https://niximagery.github.io/Something-Understood
  navbar: 
    background: primary
    search: true
    right:
      - icon: github
        href: https://github.com/NixImagery
      - icon: linkedin
        href: https://www.linkedin.com/in/niximagery/
  page-footer: 
    left: "Copyright 2024, Nick Hood." 
    background: light
    right: 
      - icon: github
        href: https://github.com/NixImagery
      - icon: linkedin
        href: https://www.linkedin.com/in/niximagery/
  page-navigation: true
  sidebar:
    contents: auto
  google-analytics: G-SBDYJL4PWN

bibliography: ../Thesis/thesis.bib
csl: ../Thesis/chicago-author-date-no-em-dash.csl

format:
  html:
    theme: yeti
    page-layout: full
    toc: false
    number-depth: 0
  pdf: 
    documentclass: scrbook
    geometry: margin=2cm, bindingoffset=0.5cm
    pagestyle: headings
    papersize: a4
    fontfamily: roboto
    fontfamilyoptions: sfdefault, light
